<a href="https://colab.research.google.com/github/MINJI-95236/2024_data-science/blob/main/0422_movie_exam(%EC%88%98%ED%96%89%ED%8F%89%EA%B0%80_%EC%97%B0%EC%8A%B5%EA%B3%BC%EC%A0%9C)_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <2013년~2024년 3월 영화 정보 데이터 분석>
* 출처: KOBIS(공식통계), 영진위에서 매년 발표하는 “한국영화연감”의 영화별 흥행기록을 참고한 것입니다.
* 2013년~2024년 3월까지의 전체 관객수를 기준으로 내림차순으로 정렬한 데이터입니다.
* 스크린수는 개봉 첫 주 최대 스크린수를 의미합니다

## 과제) 제시된 문항을 읽고 이미 제시된 결과물을 도출할 수 있도록 프로그래밍 하세요.

# 1. 데이터를 분석하는 데 필요한 패키지인 pandas와 numpy를 불러와주세요.

In [1]:
import pandas as pd
import numpy as np

# 2. pd.read_csv( )를 이용하여 영화 정보(movie_exam) 데이터를 불러온 다음 출력하세요. 이 때, ‘순번’을 인덱스로 지정합니다.

In [2]:
df = pd.read_csv('movie_exam.csv',index_col='순번')
df

,영화명,감독,개봉연도,평점,전국스크린수,전국매출액,전국관객수,서울매출액,서울관객수
순번,,,,,,,,,
1,명량,김한민,2014,8.88,"1,587","135,748,398,910","17,613,682","33,121,225,810","4,163,666"
2,극한직업,이병헌,2019,9.20,"1,978","139,647,979,516","16,264,944","31,858,660,536","3,638,287"
3,신과함께-죄와 벌,김용화,2017,8.73,"1,912","115,698,654,137","14,410,754","27,530,825,087","3,346,172"
4,국제시장,윤제균,2014,9.16,966,"110,828,014,630","14,245,998","25,842,519,330","3,233,946"
5,어벤져스: 엔드게임,"안소니 루소 , 조 루소",2019,9.50,"2,835","122,182,694,160","13,934,592","33,577,136,860","3,597,963"
6,겨울왕국 2,"크리스 벅, 제니퍼 리",2019,8.94,"2,648","114,810,421,450","13,747,792","28,824,682,580","3,225,974"
7,베테랑,류승완,2015,9.24,"1,064","105,024,756,250","13,395,400","26,766,369,950","3,290,366"
8,서울의 봄,김성수,2023,9.51,"2,328","127,924,472,553","13,127,637","29,336,838,704","2,956,510"
9,7번방의 선물,이환경,2013,8.83,787,"91,431,914,670","12,811,206","22,800,931,670","3,070,053"
10,암살,최동훈,2015,9.10,"1,519","98,463,132,781","12,705,700","25,306,651,181","3,155,960"
11,범죄도시2,이상용,2022,8.98,"2,498","131,293,353,478","12,692,959","29,072,759,869","2,755,760"
12,알라딘,가이 리치,2019,9.41,"1,311","106,983,620,359","12,555,894","30,218,911,039","3,377,404"
13,신과함께-인과 연,김용화,2018,8.63,"2,235","102,476,768,809","12,253,247","22,905,551,759","2,636,542"
14,택시운전사,장훈,2017,9.28,"1,906","95,284,747,049","12,099,971","22,186,916,199","2,729,932"
15,부산행,연상호,2016,7.17,"1,788","93,175,877,048","11,565,078","23,020,827,248","2,754,686"
16,변호인,양우석,2013,9.30,923,"82,856,578,300","11,372,451","22,571,929,000","2,978,688"
17,어벤져스: 인피니티 워,"안소니 루소 , 조 루소",2018,9.09,"2,553","99,919,006,769","11,211,880","28,631,269,069","3,008,819"
18,파묘,장재현,2024,8.21,"2,355","105,793,676,208","10,957,317","24,815,149,465","2,507,635"
19,아바타: 물의 길,제임스 카메론,2022,8.83,"2,809","137,647,702,899","10,805,065","35,476,705,140","2,623,216"
20,범죄도시3,이상용,2023,7.67,"2,582","104,687,737,771","10,682,813","22,152,818,269","2,215,433"

# 3. 전체 데이터의 행과 열의 갯수를 출력하세요.

In [4]:
df.shape

(20, 9)

# 4. 전체 데이터 중에서 '영화명'과 '평점' 정보만 출력하세요.

In [6]:
df[['영화명','개봉연도']]

             영화명  개봉연도
순번
1             명량  2014
2           극한직업  2019
3      신과함께-죄와 벌  2017
4           국제시장  2014
5     어벤져스: 엔드게임  2019
6         겨울왕국 2  2019
7            베테랑  2015
8          서울의 봄  2023
9        7번방의 선물  2013
10            암살  2015
11         범죄도시2  2022
12           알라딘  2019
13     신과함께-인과 연  2018
14         택시운전사  2017
15           부산행  2016
16           변호인  2013
17  어벤져스: 인피니티 워  2018
18            파묘  2024
19     아바타: 물의 길  2022
20         범죄도시3  2023

# 5. 2019년 이후에 개봉한 영화 데이터 중에서 '영화명'과 '개봉연도' 정보를 출력하세요.

In [7]:
df.loc[df['개봉연도'] >= 2019 ,['영화명','개봉연도']]

           영화명  개봉연도
순번
2         극한직업  2019
5   어벤져스: 엔드게임  2019
6       겨울왕국 2  2019
8        서울의 봄  2023
11       범죄도시2  2022
12         알라딘  2019
18          파묘  2024
19   아바타: 물의 길  2022
20       범죄도시3  2023

# 6. 2019년 이후에 개봉한 영화 데이터 중에서 평점이 9.0점 이상인 '영화명'과 '평점' 정보를 출력하세요.

In [8]:
df.loc[(df['개봉연도']>=2019) & (df['평점']>=9.0),['영화명','전국스크린수']]

           영화명    평점
순번
2         극한직업  9.20
5   어벤져스: 엔드게임  9.50
8        서울의 봄  9.51
12         알라딘  9.41

# 7.'서울매출액'과 '서울관객수' 정보를 삭제한 전체 데이터를 출력하세요.

In [9]:
df

,영화명,감독,개봉연도,평점,전국스크린수,전국매출액,전국관객수,서울매출액,서울관객수
순번,,,,,,,,,
1,명량,김한민,2014,8.88,"1,587","135,748,398,910","17,613,682","33,121,225,810","4,163,666"
2,극한직업,이병헌,2019,9.20,"1,978","139,647,979,516","16,264,944","31,858,660,536","3,638,287"
3,신과함께-죄와 벌,김용화,2017,8.73,"1,912","115,698,654,137","14,410,754","27,530,825,087","3,346,172"
4,국제시장,윤제균,2014,9.16,966,"110,828,014,630","14,245,998","25,842,519,330","3,233,946"
5,어벤져스: 엔드게임,"안소니 루소 , 조 루소",2019,9.50,"2,835","122,182,694,160","13,934,592","33,577,136,860","3,597,963"
6,겨울왕국 2,"크리스 벅, 제니퍼 리",2019,8.94,"2,648","114,810,421,450","13,747,792","28,824,682,580","3,225,974"
7,베테랑,류승완,2015,9.24,"1,064","105,024,756,250","13,395,400","26,766,369,950","3,290,366"
8,서울의 봄,김성수,2023,9.51,"2,328","127,924,472,553","13,127,637","29,336,838,704","2,956,510"
9,7번방의 선물,이환경,2013,8.83,787,"91,431,914,670","12,811,206","22,800,931,670","3,070,053"
10,암살,최동훈,2015,9.10,"1,519","98,463,132,781","12,705,700","25,306,651,181","3,155,960"
11,범죄도시2,이상용,2022,8.98,"2,498","131,293,353,478","12,692,959","29,072,759,869","2,755,760"
12,알라딘,가이 리치,2019,9.41,"1,311","106,983,620,359","12,555,894","30,218,911,039","3,377,404"
13,신과함께-인과 연,김용화,2018,8.63,"2,235","102,476,768,809","12,253,247","22,905,551,759","2,636,542"
14,택시운전사,장훈,2017,9.28,"1,906","95,284,747,049","12,099,971","22,186,916,199","2,729,932"
15,부산행,연상호,2016,7.17,"1,788","93,175,877,048","11,565,078","23,020,827,248","2,754,686"
16,변호인,양우석,2013,9.30,923,"82,856,578,300","11,372,451","22,571,929,000","2,978,688"
17,어벤져스: 인피니티 워,"안소니 루소 , 조 루소",2018,9.09,"2,553","99,919,006,769","11,211,880","28,631,269,069","3,008,819"
18,파묘,장재현,2024,8.21,"2,355","105,793,676,208","10,957,317","24,815,149,465","2,507,635"
19,아바타: 물의 길,제임스 카메론,2022,8.83,"2,809","137,647,702,899","10,805,065","35,476,705,140","2,623,216"
20,범죄도시3,이상용,2023,7.67,"2,582","104,687,737,771","10,682,813","22,152,818,269","2,215,433"

In [10]:
df.drop(columns = ['서울매출액','서울관객수'])

,영화명,감독,개봉연도,평점,전국스크린수,전국매출액,전국관객수
순번,,,,,,,
1,명량,김한민,2014,8.88,"1,587","135,748,398,910","17,613,682"
2,극한직업,이병헌,2019,9.20,"1,978","139,647,979,516","16,264,944"
3,신과함께-죄와 벌,김용화,2017,8.73,"1,912","115,698,654,137","14,410,754"
4,국제시장,윤제균,2014,9.16,966,"110,828,014,630","14,245,998"
5,어벤져스: 엔드게임,"안소니 루소 , 조 루소",2019,9.50,"2,835","122,182,694,160","13,934,592"
6,겨울왕국 2,"크리스 벅, 제니퍼 리",2019,8.94,"2,648","114,810,421,450","13,747,792"
7,베테랑,류승완,2015,9.24,"1,064","105,024,756,250","13,395,400"
8,서울의 봄,김성수,2023,9.51,"2,328","127,924,472,553","13,127,637"
9,7번방의 선물,이환경,2013,8.83,787,"91,431,914,670","12,811,206"
10,암살,최동훈,2015,9.10,"1,519","98,463,132,781","12,705,700"
11,범죄도시2,이상용,2022,8.98,"2,498","131,293,353,478","12,692,959"
12,알라딘,가이 리치,2019,9.41,"1,311","106,983,620,359","12,555,894"
13,신과함께-인과 연,김용화,2018,8.63,"2,235","102,476,768,809","12,253,247"
14,택시운전사,장훈,2017,9.28,"1,906","95,284,747,049","12,099,971"
15,부산행,연상호,2016,7.17,"1,788","93,175,877,048","11,565,078"
16,변호인,양우석,2013,9.30,923,"82,856,578,300","11,372,451"
17,어벤져스: 인피니티 워,"안소니 루소 , 조 루소",2018,9.09,"2,553","99,919,006,769","11,211,880"
18,파묘,장재현,2024,8.21,"2,355","105,793,676,208","10,957,317"
19,아바타: 물의 길,제임스 카메론,2022,8.83,"2,809","137,647,702,899","10,805,065"
20,범죄도시3,이상용,2023,7.67,"2,582","104,687,737,771","10,682,813"

# 8. 전체 데이터를 '평점' 기준 내림차순으로 출력하세요.

In [13]:
df.sort_values('평점',ascending=False)

,영화명,감독,개봉연도,평점,전국스크린수,전국매출액,전국관객수,서울매출액,서울관객수
순번,,,,,,,,,
8,서울의 봄,김성수,2023,9.51,"2,328","127,924,472,553","13,127,637","29,336,838,704","2,956,510"
5,어벤져스: 엔드게임,"안소니 루소 , 조 루소",2019,9.50,"2,835","122,182,694,160","13,934,592","33,577,136,860","3,597,963"
12,알라딘,가이 리치,2019,9.41,"1,311","106,983,620,359","12,555,894","30,218,911,039","3,377,404"
16,변호인,양우석,2013,9.30,923,"82,856,578,300","11,372,451","22,571,929,000","2,978,688"
14,택시운전사,장훈,2017,9.28,"1,906","95,284,747,049","12,099,971","22,186,916,199","2,729,932"
7,베테랑,류승완,2015,9.24,"1,064","105,024,756,250","13,395,400","26,766,369,950","3,290,366"
2,극한직업,이병헌,2019,9.20,"1,978","139,647,979,516","16,264,944","31,858,660,536","3,638,287"
4,국제시장,윤제균,2014,9.16,966,"110,828,014,630","14,245,998","25,842,519,330","3,233,946"
10,암살,최동훈,2015,9.10,"1,519","98,463,132,781","12,705,700","25,306,651,181","3,155,960"
17,어벤져스: 인피니티 워,"안소니 루소 , 조 루소",2018,9.09,"2,553","99,919,006,769","11,211,880","28,631,269,069","3,008,819"
11,범죄도시2,이상용,2022,8.98,"2,498","131,293,353,478","12,692,959","29,072,759,869","2,755,760"
6,겨울왕국 2,"크리스 벅, 제니퍼 리",2019,8.94,"2,648","114,810,421,450","13,747,792","28,824,682,580","3,225,974"
1,명량,김한민,2014,8.88,"1,587","135,748,398,910","17,613,682","33,121,225,810","4,163,666"
9,7번방의 선물,이환경,2013,8.83,787,"91,431,914,670","12,811,206","22,800,931,670","3,070,053"
19,아바타: 물의 길,제임스 카메론,2022,8.83,"2,809","137,647,702,899","10,805,065","35,476,705,140","2,623,216"
3,신과함께-죄와 벌,김용화,2017,8.73,"1,912","115,698,654,137","14,410,754","27,530,825,087","3,346,172"
13,신과함께-인과 연,김용화,2018,8.63,"2,235","102,476,768,809","12,253,247","22,905,551,759","2,636,542"
18,파묘,장재현,2024,8.21,"2,355","105,793,676,208","10,957,317","24,815,149,465","2,507,635"
20,범죄도시3,이상용,2023,7.67,"2,582","104,687,737,771","10,682,813","22,152,818,269","2,215,433"
15,부산행,연상호,2016,7.17,"1,788","93,175,877,048","11,565,078","23,020,827,248","2,754,686"